<script lang="ts">
	import Slide from "./Slide.svelte";
</script>

<Slide animate>
	<Slide animate bgGradient="linear-gradient(to top, #283b95, #17b2c3)">
		<h1>Hello, folks 👋</h1>
	</Slide>

	<Slide animate bgGradient="linear-gradient(to right, #283b95, #17b2c3)">
		<h1>Hello, folks 👋</h1>
		<p>My name is Todor and I work as...</p>
	</Slide>

	<Slide animate bgGradient="linear-gradient(to bottom, #283b95, #17b2c3)">
		<h1>Hello, folks 👋</h1>
		<p>My name is Todor and I work as...</p>
		<p>🥁</p>
	</Slide>

	<Slide animate bgGradient="linear-gradient(to left,#283b95, #17b2c3)">
		<h1>Hello, folks 👋</h1>
		<p>My name is Todor and I work as...</p>
		<p>🥁</p>
		<p>Software Engineer💻</p>
	</Slide>
</Slide>

<Slide animate bgGradient="radial-gradient(#8E24AA, #673AB7)">
	<Slide animate>
		<p>
			I am a web developer with 5 years of experience in both front-end and back-end development.
			Throughout my career, I have worked extensively with technologies like <span class="em">React</span>, <span class="em">Angular</span>, and
			<span class="em">NestJS</span>, gaining deep expertise in building robust and dynamic web applications. Recently, I
			have been particularly drawn to <span class="em">SvelteKit</span>, as its innovative approach to front-end development
			has captured my interest.
		</p>
	</Slide>

	<Slide animate>
		<p>
			I thrive on crafting intuitive user experiences and collaborating with teams to bring creative
			ideas to life. My journey in web development has equipped me with a solid foundation in <span class="em">HTML</span>,
			<span class="em">CSS</span>, and <span class="em">JavaScript</span>, allowing me to create visually appealing and responsive interfaces. I
			have a strong grasp of front-end frameworks like <span class="em">React</span> and <span class="em">Angular</span>, leveraging their power to
			develop scalable and efficient applications.
		</p>
	</Slide>

	<Slide animate>
		<p>
			On the back-end side, I have honed my skills in <span class="em">Node.js</span> and have found great satisfaction in
			working with <span class="em">NestJS</span>, a framework that promotes modular and scalable server-side development.
			This combination of front-end and back-end expertise enables me to seamlessly bridge the gap
			between different layers of an application.
		</p>
	</Slide>

	<Slide animate>
		<p>
			Currently, my passion lies in exploring the possibilities of <span class="em">SvelteKit</span>. Its reactive approach,
			minimalistic nature, and exceptional performance have captured my attention, and I'm eagerly
			diving into this exciting framework to create dynamic and efficient web applications.
		</p>
	</Slide>

	<Slide animate>
		<p>
			I am constantly seeking new challenges and opportunities to expand my knowledge and skills in
			the ever-evolving landscape of web development. I am thrilled to contribute my experience and
			enthusiasm to projects that push the boundaries of what's possible on the web.
		</p>
	</Slide>

	<Slide animate>
		<p>
			Everything above was generated by my dear friend <span class="em">ChatGPT</span> 😁
		</p>
	</Slide>
</Slide>

<style>
	.em {
		color: #a8d62b;
	}
</style>
